const fs = require('fs');

const file = '/Users/jarnosaarinen/subsoccer/translations.js';
let content = fs.readFileSync(file, 'utf8');

const TRANSLATION_MAP = {
    fr: {
        rules_and_guide: "RÈGLES & GUIDE",
        rules_official_rules: "RÈGLES OFFICIELLES",
        rules_host_tournament: "COMMENT ORGANISER UN TOURNOI",
        rules_btn_close: "FERMER",
        rules_start_title: "DÉBUT",
        rules_start_desc: "Le vainqueur du Chifoumi (Pierre-Feuille-Ciseaux) commence.",
        rules_kickoff_title: "COUP D'ENVOI",
        rules_kickoff_desc: "Le coup d'envoi doit être pris à l'intérieur de votre propre zone de but.",
        rules_position_title: "POSITIONNEMENT",
        rules_position_desc: "Les deux fesses doivent rester sur le banc. Les mains ne doivent pas entrer dans la zone de jeu et doivent être gardées sur la table ou sur les côtés des bancs.",
        rules_ballout_title: "BALLON HORS-JEU",
        rules_ballout_desc: "Si le ballon sort de la table, le jeu reprend par un coup d'envoi du joueur du côté duquel le ballon est sorti.",
        rules_winner_title: "VAINQUEUR",
        rules_winner_desc: "Le premier joueur à marquer 3 buts gagne.",
        host_step1_title: "SÉLECTIONNER 2 À 8 JOUEURS",
        host_step1_desc: "Saisissez les noms des joueurs et commencez le tournoi.",
        host_step2_title: "TABLEAU AUTOMATIQUE",
        host_step2_desc: "Subsoccer GO mélange les matchs et génère le tableau du tournoi automatiquement. Si le nombre de joueurs est impair (ex. 3 ou 5 joueurs), l'application attribue des laissez-passer (BYE) pour le premier tour.",
        host_step3_title: "VAINQUEUR & FORFAIT",
        host_step3_desc: "Indiquez le vainqueur en cliquant sur le nom du joueur dans le tableau. Si un joueur déclare forfait, désignez l'adversaire comme vainqueur.",
        host_step4_title: "GRANDS TOURNOIS",
        host_step4_desc: "Organisez plusieurs poules de qualification séparées (max 8 joueurs par poule). Sélectionnez les 1 à 4 meilleurs joueurs de chaque poule et créez un nouveau \"tournoi final\" dans l'application pour désigner le champion général."
    },
    es: {
        rules_and_guide: "REGLAS & GUÍA",
        rules_official_rules: "REGLAS OFICIALES",
        rules_host_tournament: "CÓMO ORGANIZAR UN TORNEO",
        rules_btn_close: "CERRAR",
        rules_start_title: "INICIO",
        rules_start_desc: "El ganador de Piedra, Papel o Tijera saca primero.",
        rules_kickoff_title: "SAQUE DE CENTRO",
        rules_kickoff_desc: "El saque debe realizarse dentro de tu propia área de portería.",
        rules_position_title: "POSICIÓN",
        rules_position_desc: "Ambos glúteos deben permanecer en el banco. Las manos no deben entrar en el área de juego y deben mantenerse sobre la mesa o a los lados de los bancos.",
        rules_ballout_title: "BALÓN FUERA DE JUEGO",
        rules_ballout_desc: "Si el balón sale de la mesa, el juego se reanuda con un saque del jugador por cuyo lado salió el balón.",
        rules_winner_title: "GANADOR",
        rules_winner_desc: "El primer jugador en marcar 3 goles gana.",
        host_step1_title: "SELECCIONA 2-8 JUGADORES",
        host_step1_desc: "Introduce los nombres de los jugadores y comienza el torneo.",
        host_step2_title: "CUADRO AUTOMÁTICO",
        host_step2_desc: "Subsoccer GO sortea los partidos y genera el cuadro del torneo automáticamente. Si el número de jugadores es impar (ej. 3 o 5), la app asigna pases libres (BYE) en la primera ronda.",
        host_step3_title: "GANADOR DEL PARTIDO Y RETIRADA",
        host_step3_desc: "Marca al ganador pulsando su nombre en el cuadro. Si un jugador se retira, marca al oponente como ganador.",
        host_step4_title: "TORNEOS GRANDES",
        host_step4_desc: "Organiza varios grupos de clasificación separados (máx. 8 jugadores por grupo). Elige a los mejores 1–4 de cada grupo y crea un nuevo torneo final en la app para coronar al campeón absoluto."
    },
    de: {
        rules_and_guide: "REGELN & ANLEITUNG",
        rules_official_rules: "OFFIZIELLE REGELN",
        rules_host_tournament: "TURNIER VERANSTALTEN",
        rules_btn_close: "SCHLIESSEN",
        rules_start_title: "START",
        rules_start_desc: "Wer Schere-Stein-Papier gewinnt, beginnt.",
        rules_kickoff_title: "ANSTOSS",
        rules_kickoff_desc: "Der Anstoß muss aus dem eigenen Torraum erfolgen.",
        rules_position_title: "POSITIONIERUNG",
        rules_position_desc: "Beide Gesäßhälften müssen auf der Bank bleiben. Die Hände dürfen das Spielfeld nicht betreten und sollten auf dem Tisch oder an den Seiten der Bänke gehalten werden.",
        rules_ballout_title: "BALL IM AUS",
        rules_ballout_desc: "Verlässt der Ball das Spielfeld, wird das Spiel mit einem Anstoß des Spielers fortgesetzt, auf dessen Seite der Ball das Feld verlassen hat.",
        rules_winner_title: "SIEGER",
        rules_winner_desc: "Wer zuerst 3 Tore erzielt, gewinnt.",
        host_step1_title: "2-8 SPIELER WÄHLEN",
        host_step1_desc: "Spielernamen eingeben und das Turnier starten.",
        host_step2_title: "AUTOMATISCHER SPIELPLAN",
        host_step2_desc: "Subsoccer GO mischt die Partien und erstellt automatisch den Turnierbaum. Bei ungerader Spieleranzahl (z. B. 3 oder 5 Spieler) vergibt die App in der ersten Runde Freilose (BYE).",
        host_step3_title: "SIEGER & AUFGABE",
        host_step3_desc: "Markieren Sie den Sieger, indem Sie auf den Spielernamen klicken. Tritt ein Spieler nicht an oder gibt auf, werten Sie den Gegner als Sieger.",
        host_step4_title: "GROSSE TURNIERE",
        host_step4_desc: "Veranstalten Sie mehrere getrennte Qualifikationsgruppen (max. 8 Spieler pro Gruppe). Wählen Sie die besten 1–4 Spieler jeder Gruppe und erstellen Sie ein neues Finalturnier, um den Gesamtsieger zu krönen."
    },
    pt: {
        rules_and_guide: "REGRAS & GUIA",
        rules_official_rules: "REGRAS OFICIAIS",
        rules_host_tournament: "COMO ORGANIZAR UM TORNEO",
        rules_btn_close: "FECHAR",
        rules_start_title: "INÍCIO",
        rules_start_desc: "O vencedor do Pedra, Papel ou Tesoura começa.",
        rules_kickoff_title: "PONTAPÉ DE SAÍDA",
        rules_kickoff_desc: "O pontapé de saída deve ser feito dentro da sua própria área de baliza.",
        rules_position_title: "POSICIONAMENTO",
        rules_position_desc: "Ambas as nádegas devem permanecer no banco. As mãos não devem entrar na área de jogo e devem ser mantidas na mesa ou nas laterais dos bancos.",
        rules_ballout_title: "BOLA FORA DE JOGO",
        rules_ballout_desc: "Se a bola sair da mesa, o jogo recomeça com um pontapé de saída do jogador pelo lado do qual a bola saiu.",
        rules_winner_title: "VENCEDOR",
        rules_winner_desc: "O primeiro jogador a marcar 3 golos vence.",
        host_step1_title: "SELECIONE 2-8 JOGADORES",
        host_step1_desc: "Insira os nomes dos jogadores e inicie o torneio.",
        host_step2_title: "CHAVES AUTOMÁTICAS",
        host_step2_desc: "O Subsoccer GO embaralha os jogos e gera a chave do torneio automaticamente. Se o número de jogadores for ímpar (ex: 3 ou 5), o aplicativo atribui folgas (BYE) para a primeira rodada.",
        host_step3_title: "VENCEDOR DO JOGO & DESISTÊNCIA",
        host_step3_desc: "Marque o vencedor clicando no nome do jogador na chave. Se um jogador desistir, marque o oponente como vencedor.",
        host_step4_title: "GRANDES TORNEIOS",
        host_step4_desc: "Organize vários grupos de qualificação separados (máx. 8 jogadores por grupo). Escolha os melhores 1–4 jogadores de cada grupo e crie um novo torneio final no aplicativo para coroar o campeão geral."
    },
    sv: {
        rules_and_guide: "REGLER & GUIDE",
        rules_official_rules: "OFFICIELLA REGLER",
        rules_host_tournament: "HUR MAN ARRANGERAR EN TURNERING",
        rules_btn_close: "STÄNG",
        rules_start_title: "START",
        rules_start_desc: "Vinnaren av sten-sax-påse börjar.",
        rules_kickoff_title: "AVSPARK",
        rules_kickoff_desc: "Avspark måste läggas inom ditt eget målområde.",
        rules_position_title: "POSITIONERING",
        rules_position_desc: "Båda skinkorna måste förbli på bänken. Händerna får inte komma in i spelområdet och bör hållas på bordet eller på sidorna av bänkarna.",
        rules_ballout_title: "BOLL UR SPEL",
        rules_ballout_desc: "Om bollen lämnar bordet återupptas spelet med en avspark av den spelare från vars sida bollen gick ut.",
        rules_winner_title: "VINNARE",
        rules_winner_desc: "Den första spelaren som gör 3 mål vinner.",
        host_step1_title: "VÄLJ 2-8 SPELARE",
        host_step1_desc: "Ange spelarnamn och starta turneringen.",
        host_step2_title: "AUTOMATISK LOTTNING",
        host_step2_desc: "Subsoccer GO blandar matcherna och genererar turneringens spelschema automatiskt. Om antalet spelare är ojämnt (t.ex. 3 eller 5 spelare) tilldelar appen frispel (BYE) i första omgången.",
        host_step3_title: "MATCHVINNARE & W.O.",
        host_step3_desc: "Markera vinnaren genom att klicka på spelarens namn i spelschemat. Om en spelare lämnar walkover, markera motståndaren som vinnare.",
        host_step4_title: "STORA TURNERINGAR",
        host_step4_desc: "Arrangera flera separata kvalgrupper (max 8 spelare per grupp). Välj de 1–4 bästa spelarna från varje grupp och skapa en ny slutspelsturnering i appen för att kora den slutliga mästaren."
    },
    nb: {
        rules_and_guide: "REGLER & GUIDE",
        rules_official_rules: "OFFISIELLE REGLER",
        rules_host_tournament: "SLIK ARRANGERER DU EN TURNERING",
        rules_btn_close: "LUKK",
        rules_start_title: "START",
        rules_start_desc: "Vinneren av stein-saks-papir starter.",
        rules_kickoff_title: "AVSPARK",
        rules_kickoff_desc: "Avspark må tas innenfor ditt eget målområde.",
        rules_position_title: "POSISJONERING",
        rules_position_desc: "Begge rumpeballene må forbli på benken. Hendene må ikke komme inn i spilleområdet og skal holdes på bordet eller på sidene av benkene.",
        rules_ballout_title: "BALL UT AV SPILL",
        rules_ballout_desc: "Hvis ballen forlater bordet, gjenopptas spillet med avspark fra den spilleren som hadde ballen ut på sin side.",
        rules_winner_title: "VINNER",
        rules_winner_desc: "Den første spilleren som scorer 3 mål vinner.",
        host_step1_title: "VELG 2-8 SPILLERE",
        host_step1_desc: "Tast inn spillernavn og start turneringen.",
        host_step2_title: "AUTOMATISK OPPSETT",
        host_step2_desc: "Subsoccer GO trekker kampene og genererer turneringsskjemaet automatisk. Hvis spillerantallet er ujevnt (f.eks. 3 or 5 spillere), tildeler appen walkover (BYE) for første runde.",
        host_step3_title: "KAMPVINNER & WALKOUT",
        host_step3_desc: "Marker vinneren ved å trykke på spillerens navn i oppsettet. Hvis en spiller trekker seg, markerer du motstanderen som vinner.",
        host_step4_title: "STORE TURNERINGER",
        host_step4_desc: "Arranger flere separate kvalifiseringsgrupper (maks 8 spillere per gruppe). Velg de 1–4 beste spillerne fra hver gruppe og opprett en ny finaleturnering i appen for å kåre mesteren."
    },
    da: {
        rules_and_guide: "REGLER & GUIDE",
        rules_official_rules: "OFFICIELLE REGLER",
        rules_host_tournament: "SÅDAN AFHOLDER DU EN TURNERING",
        rules_btn_close: "LUK",
        rules_start_title: "START",
        rules_start_desc: "Vinderen af sten-saks-papir starter.",
        rules_kickoff_title: "IGANGSÆTNING",
        rules_kickoff_desc: "Igangsætning skal tages inde i dit eget målfelt.",
        rules_position_title: "POSITIONERING",
        rules_position_desc: "Begge balder skal forblive på bænken. Hænderne må ikke komme ind i spilleområdet og skal holdes på bordet eller på siderne af bænkene.",
        rules_ballout_title: "BOLD UDE AF SPIL",
        rules_ballout_desc: "Hvis bolden forlader bordet, genoptages spillet med igangsætning af den spiller, fra hvis side bolden røg ud.",
        rules_winner_title: "VINDER",
        rules_winner_desc: "Den første spiller, der scorer 3 mål, vinder.",
        host_step1_title: "VÆLG 2-8 SPILLERE",
        host_step1_desc: "Indtast spillernavne og start turneringen.",
        host_step2_title: "AUTOMATISK TURNERINGSPLAN",
        host_step2_desc: "Subsoccer GO blander kampene og genererer turneringsplanen automatisk. Hvis spillerantallet er ulige (f.eks. 3 eller 5 spillere), tildeler appen oversiddere (BYE) i eerste runde.",
        host_step3_title: "KAMPVINDER & AFBUD",
        host_step3_desc: "Marker vinneren ved at klikke på spillerens navn i turneringsplanen. Hvis en spiller melder afbud, markeres modstanderen som vinder.",
        host_step4_title: "STORE TURNERINGER",
        host_step4_desc: "Afhold flere separate kvalifikationspuljer (maks. 8 spillere per pulje). Vælg de bedste 1–4 spillere fra hver pulje og opret en ny finaleturnering i appen for at kåre den samlede vinder."
    },
    it: {
        rules_and_guide: "REGOLE & GUIDA",
        rules_official_rules: "REGOLE UFFICIALI",
        rules_host_tournament: "COME GESTIRE UN TORNEO",
        rules_btn_close: "CHIUDI",
        rules_start_title: "INIZIO",
        rules_start_desc: "Il vincitore di Carta-Forbice-Sasso inizia il gioco.",
        rules_kickoff_title: "CALCIO D'INIZIO",
        rules_kickoff_desc: "Calcio d'inizio deve essere battuto all'interno della propria area di porta.",
        rules_position_title: "POSIZIONAMENTO",
        rules_position_desc: "Entrambe le natiche devono rimanere sulla panchina. Le mani non devono entrare nell'area di gioco e devono essere tenute sul tavolo o sui lati delle panchine.",
        rules_ballout_title: "PALLA FUORI",
        rules_ballout_desc: "Se la palla esce dal tavolo, il gioco riprende con un calcio d'inizio da parte del giocatore dal cui lato è uscita la palla.",
        rules_winner_title: "VINCITORE",
        rules_winner_desc: "Il primo giocatore a segnare 3 gol vince.",
        host_step1_title: "SELEZIONA 2-8 GIOCATORI",
        host_step1_desc: "Inserisci i nomi dei giocatori e inizia il torneo.",
        host_step2_title: "TABELLONE AUTOMATICO",
        host_step2_desc: "Subsoccer GO organizza le partite e genera automaticamente il tabellone del torneo. Se il numero di giocatori è dispari (es. 3 o 5), l'app assegna passaggi del turno automatici (BYE) per il primo turno.",
        host_step3_title: "VINCITORE INCONTRO & RITIRO",
        host_step3_desc: "Segna il vincitore cliccando sul nome del giocatore nel tabellone. Se un giocatore si ritira, assegna la vittoria all'avversario.",
        host_step4_title: "TORNEI GRANDI",
        host_step4_desc: "Crea più gironi di qualificazione separati (max 8 giocatori per girone). Seleziona i migliori 1-4 giocatori di ogni girone e crea un nuovo \"torneo finale\" nell'app per decretare il campione assoluto."
    },
    nl: {
        rules_and_guide: "SPELREGELS & GIDS",
        rules_official_rules: "OFFICIËLE SPELREGELS",
        rules_host_tournament: "EEN TOERNOOI ORGANISEREN",
        rules_btn_close: "SLUITEN",
        rules_start_title: "START",
        rules_start_desc: "De winnaar van Steen-Papier-Schaar begint.",
        rules_kickoff_title: "AFTRAP",
        rules_kickoff_desc: "De aftrap moet vanuit je eigen doelgebied worden genomen.",
        rules_position_title: "POSITIONERING",
        rules_position_desc: "Beide billen moeten op de bank blijven. Handen mogen het speelveld niet betreden en moeten op de tafel of aan de zijkant van de banken worden gehouden.",
        rules_ballout_title: "BAL BUITEN SPEL",
        rules_ballout_desc: "Als de bal de tafel verlaat, wordt het spel hervat met een aftrap door de speler aan wiens kant de bal uitging.",
        rules_winner_title: "WINNAAR",
        rules_winner_desc: "De speler die als eerste 3 doelpunten scoort, wint.",
        host_step1_title: "SELECTEER 2-8 SPELERS",
        host_step1_desc: "Voer de namen van de spelers in en start het toernooi.",
        host_step2_title: "AUTOMATISCH SCHEMA",
        host_step2_desc: "Subsoccer GO schudt de wedstrijden en genereert automatisch het toernooischema. Als het aantal spelers oneven is (bijv. 3 of 5), wijst de app vrijstellingen (BYE) toe voor de eerste ronde.",
        host_step3_title: "WEDSTRIJDWINNAAR & FORFAIT",
        host_step3_desc: "Markeer de winnaar door op de naam van de speler in het schema te klikken. Als een speler opgeeft, markeer dan de tegenstander als winnaar.",
        host_step4_title: "GROTE TOERNOOIEN",
        host_step4_desc: "Organiseer meerdere afzonderlijke kwalificatiepoules (max. 8 spelers per poule). Kies de beste 1-4 spelers uit elke poule en maak een nieuw \"finaletoernooi\" aan in de app om de algehele kampioen te kronen."
    },
    cs: {
        rules_and_guide: "PRAVIDLA & NÁVOD",
        rules_official_rules: "OFICIÁLNÍ PRAVIDLA",
        rules_host_tournament: "JAK USPOŘÁDAT TURNAJ",
        rules_btn_close: "ZAVŘÍT",
        rules_start_title: "START",
        rules_start_desc: "Hru zahajuje vítěz hry Kámen-Nůžky-Papír.",
        rules_kickoff_title: "VÝKOP",
        rules_kickoff_desc: "Výkop musí být proveden z vašeho vlastního brankového území.",
        rules_position_title: "POZICE",
        rules_position_desc: "Obě poloviny hýždí musí zůstat na lavičce. Ruce nesmí vstoupit do hrací plochy a měly by zůstat na stole nebo na bocích laviček.",
        rules_ballout_title: "MÍČ MIMO HRU",
        rules_ballout_desc: "Pokud míč opustí stůl, hra se restartuje výkopem hráče, na jehož straně míč stůl opustil.",
        rules_winner_title: "VÍTĚZ",
        rules_winner_desc: "Vítězí hráč, který jako první vstřelí 3 góly.",
        host_step1_title: "ZVOLTE 2-8 HRÁČŮ",
        host_step1_desc: "Zadejte jména hráčů a spusťte turnaj.",
        host_step2_title: "AUTOMATICKÝ PAVOUK",
        host_step2_desc: "Subsoccer GO vylosuje zápasy a automaticky vygeneruje turnajového pavouka. Pokud je počet hráčů lichý (např. 3 nebo 5), aplikace přidělí volné losy (BYE) pro první kolo.",
        host_step3_title: "VÍTĚZ ZÁPASU A KONTUMACE",
        host_step3_desc: "Označte vítěze kliknutím na jméno hráče v pavouku. Pokud hráč odstoupí, označte jako vítěze jeho soupeře.",
        host_step4_title: "VELKÉ TURNAJE",
        host_step4_desc: "Uspořádejte více samostatných kvalifikačních skupin (max. 8 hráčů ve skupině). Vyberte 1–4 nejlepší hráče z každé skupiny a vytvořte v aplikaci nový \"finálový turnaj\", který určí celkového šampiona."
    },
    tr: {
        rules_and_guide: "KURALLAR & REHBER",
        rules_official_rules: "RESMİ KURALLAR",
        rules_host_tournament: "TURNUVA NASIL DÜZENLENİR",
        rules_btn_close: "KAPAT",
        rules_start_title: "BAŞLANGIÇ",
        rules_start_desc: "Taş-Kağıt-Makas oyununu kazanan başlar.",
        rules_kickoff_title: "BAŞLAMA VURUŞU",
        rules_kickoff_desc: "Başlama vuruşu kendi kale alanınızın içinden yapılmalıdır.",
        rules_position_title: "POZİSYON ALMA",
        rules_position_desc: "Her iki kalça da bankta kalmalıdır. Eller oyun alanına girmemeli, masanın üzerinde veya bankların yan kısımlarında tutulmalıdır.",
        rules_ballout_title: "TOP OYUN DIŞI",
        rules_ballout_desc: "Top masadan çıkarsa oyun, topun çıktığı taraftaki oyuncunun başlama vuruşu yapmasıyla yeniden başlar.",
        rules_winner_title: "KAZANAN",
        rules_winner_desc: "3 gol atan ilk oyuncu kazanır.",
        host_step1_title: "2-8 OYUNCU SEÇİN",
        host_step1_desc: "Oyuncu isimlerini girin ve turnuvayı başlatın.",
        host_step2_title: "OTOMATİK FİKSTÜR",
        host_step2_desc: "Subsoccer GO maçları karıştırır ve turnuva fikstürünü otomatik oluşturur. Oyuncu sayısı tekse (örn. 3 veya 5 oyuncu), uygulama ilk tur için bay (BYE) hakkı atar.",
        host_step3_title: "MAÇ KAZANANI & HÜKMEN",
        host_step3_desc: "Fikstürde oyuncunun ismine tıklayarak kazananı belirleyin. Bir oyuncu çekilirse, rakibini kazanan olarak işaretleyin.",
        host_step4_title: "BÜYÜK TURNUVALAR",
        host_step4_desc: "Birden fazla ayrı eleme grubu düzenleyin (grup başına en fazla 8 oyuncu). Her gruptan ilk 1-4 oyuncuyu seçip şampiyonu belirlemek için uygulamada yeni bir \"final turnuvası\" oluşturun."
    },
    hu: {
        rules_and_guide: "SZABÁLYOK & ÚTMUTATÓ",
        rules_official_rules: "HIVATALOS SZABÁLYOK",
        rules_host_tournament: "HOGYAN RENDEZZÜNK TORNÁT",
        rules_btn_close: "BEZÁRÁS",
        rules_start_title: "START",
        rules_start_desc: "A Kő-Papír-Olló játék nyertese kezd.",
        rules_kickoff_title: "KEZDŐRÚGÁS",
        rules_kickoff_desc: "A kezdőrúgást a saját kapuelőteredből kell elvégezni.",
        rules_position_title: "POZÍCIONÁLÁS",
        rules_position_desc: "Mindkét ülepnek a padon kell maradnia. A kezek nem léphetnek be a játékterületre; azokat az asztalon vagy a padok oldalán kell tartani.",
        rules_ballout_title: "KIPORDULT LABDA",
        rules_ballout_desc: "Ha a labda elhagyja az asztalt, a játék azon játékos kezdőrúgásával folytatódik, akinek az oldalán a labda kiment.",
        rules_winner_title: "GYŐZTES",
        rules_winner_desc: "Az a játékos nyer, aki először szerez 3 gólt.",
        host_step1_title: "VÁLASSZON 2-8 JÁTÉKOST",
        host_step1_desc: "Adja meg a játékosok nevét, és indítsa el a tornát.",
        host_step2_title: "AUTOMATIKUS SORSOLÁS",
        host_step2_desc: "A Subsoccer GO kisorsolja a meccseket és automatikusan elkészíti a tornatáblát. Páratlan létszám esetén (pl. 3 vagy 5 játékos) az app erőnyerőket (BYE) jelöl ki az első körben.",
        host_step3_title: "MECCS GYŐZTESE ÉS JÁTÉK NÉLKÜL",
        host_step3_desc: "Jelölje meg a győztest a nevére kattintva a táblán. Ha egy játékos visszalép, jelölje meg az ellenfelet győztesként.",
        host_step4_title: "NAGY TORNÁK",
        host_step4_desc: "Rendezzen több különálló selejtezőcsoportot (csoportonként max. 8 fő). Válassza ki a csoportok 1–4. helyezettjeit, majd hozzon létre egy új \"döntő tornát\" az alkalmazásban a végső győztes eldöntéséhez."
    },
    id: {
        rules_and_guide: "ATURAN & PANDUAN",
        rules_official_rules: "ATURAN RESMI",
        rules_host_tournament: "CARA MENGADAKAN TURNAMEN",
        rules_btn_close: "TUTUP",
        rules_start_title: "MULAI",
        rules_start_desc: "Pemenang Gunting/Batu/Kertas memulai permainan.",
        rules_kickoff_title: "KICK-OFF",
        rules_kickoff_desc: "Kick-off harus dilakukan dari dalam area gawang Anda sendiri.",
        rules_position_title: "POSISI",
        rules_position_desc: "Kedua bokong harus tetap berada di bangku. Tangan tidak boleh memasuki area permainan dan harus tetap berada di meja atau di samping bangku.",
        rules_ballout_title: "BOLA KELUAR",
        rules_ballout_desc: "Jika bola keluar meja, permainan dimulai kembali dengan kick-off oleh pemain yang menjadi sisi keluarnya bola.",
        rules_winner_title: "PEMENANG",
        rules_winner_desc: "Pemain pertama yang mencetak 3 gol menang.",
        host_step1_title: "PILIH 2-8 PEMAIN",
        host_step1_desc: "Masukkan nama pemain dan mulai turnamen.",
        host_step2_title: "BAGAN OTOMATIS",
        host_step2_desc: "Subsoccer GO mengacak pertandingan dan membuat bagan turnamen secara otomatis. Jika jumlah pemain ganjil (misal 3 atau 5 pemain), aplikasi memberikan kemenangan bye (BYE) pada babak pertama.",
        host_step3_title: "PEMENANG PERTANDINGAN & HUKUMAN",
        host_step3_desc: "Tentukan pemenang dengan mengeklik nama pemain pada bagan. Jika ada pemain yang mundur, tandai lawan sebagai pemenang.",
        host_step4_title: "TURNAMEN BESAR",
        host_step4_desc: "Adakan beberapa grup kualifikasi terpisah (maks. 8 pemain per grup). Pilih 1-4 pemain teratas dari setiap grup dan buat \"turnamen final\" baru di aplikasi untuk menentukan juara umum."
    },
    vi: {
        rules_and_guide: "LUẬT & HƯỚNG DẪN",
        rules_official_rules: "LUẬT CHƠI CHÍNH THỨC",
        rules_host_tournament: "CÁCH TỔ CHỨC GIẢI ĐẤU",
        rules_btn_close: "ĐÓNG",
        rules_start_title: "BẮT ĐẦU",
        rules_start_desc: "Người thắng trò chơi Kéo/Búa/Bao sẽ bắt đầu trước.",
        rules_kickoff_title: "KICK-OFF",
        rules_kickoff_desc: "Cú đá giao bóng (kick-off) phải được thực hiện bên trong khu vực khung thành của bạn.",
        rules_position_title: "TƯ THẾ CHƠI",
        rules_position_desc: "Cả hai mông phải luôn chạm vào băng ghế. Bàn tay không được đưa vào khu vực sân chơi và phải đặt trên bàn hoặc hai bên băng ghế.",
        rules_ballout_title: "BÓNG RA NGOÀI",
        rules_ballout_desc: "Nếu bóng ra ngoài bàn, trận đấu được tiếp tục bằng cú giao bóng của cầu thủ ở bên phía bóng đi ra ngoài.",
        rules_winner_title: "NGƯỜI THẮNG",
        rules_winner_desc: "Người chơi đầu tiên ghi được 3 bàn thắng sẽ thắng cuộc.",
        host_step1_title: "CHỌN 2-8 CẦU THỦ",
        host_step1_desc: "Nhập tên cầu thủ và bắt đầu giải đấu.",
        host_step2_title: "PHÂN CẶP TỰ ĐỘNG",
        host_step2_desc: "Subsoccer GO sẽ xáo trộn các trận đấu và tự động tạo sơ đồ giải đấu. Nếu số lượng cầu thủ là số lẻ (ví dụ: 3 hoặc 5), ứng dụng sẽ tự động phân lượt đi tiếp miễn phí (BYE) cho vòng đầu tiên.",
        host_step3_title: "GHI NHẬN KẾT QUẢ & BỎ CUỘC",
        host_step3_desc: "Chọn người thắng bằng cách nhấp vào tên cầu thủ trên sơ đồ. Nếu một cầu thủ bỏ cuộc, hãy ghi nhận đối thủ là người chiến thắng.",
        host_step4_title: "CÁC GIẢI ĐẤU LỚN",
        host_step4_desc: "Tổ chức nhiều bảng đấu loại riêng biệt (tối đa 8 cầu thủ mỗi bảng). Chọn 1-4 cầu thủ đứng đầu từ mỗi bảng và tạo một \"giải đấu chung kết\" mới trong ứng dụng để tìm ra nhà vô địch tổng."
    },
    pl: {
        rules_and_guide: "ZASADY & PORADNIK",
        rules_official_rules: "ZASADY OFICJALNE",
        rules_host_tournament: "JAK ZORGANIZOWAĆ TURNIEJ",
        rules_btn_close: "ZAMKNIJ",
        rules_start_title: "START",
        rules_start_desc: "Zaczyna zwycięzca gry w Kamień-Papier-Nożyce.",
        rules_kickoff_title: "ROZPOCZĘCIE",
        rules_kickoff_desc: "Rozpoczęcie gry musi nastąpić z własnego pola bramkowego.",
        rules_position_title: "POZYCJA",
        rules_position_desc: "Oba pośladki muszą cały czas przylegać do ławki. Dłonie nie mogą wchodzić w obszar gry i powinny być trzymane na stole lub po bokach ławek.",
        rules_ballout_title: "PIŁKA POZA GRĄ",
        rules_ballout_desc: "Jeśli piłka opuści stół, gra jest wznawiana rozpoczęciem przez gracza, po którego stronie piłka wypadła.",
        rules_winner_title: "ZWYCIĘZCA",
        rules_winner_desc: "Wygrywa gracz, który jako pierwszy zdobędzie 3 bramki.",
        host_step1_title: "WYBIERZ 2-8 GRACZY",
        host_step1_desc: "Wpisz imiona graczy i rozpocznij turniej.",
        host_step2_title: "AUTOMATYCZNA DRABINKA",
        host_step2_desc: "Subsoccer GO losuje mecze i automatycznie generuje drabinkę turniejową. Jeśli liczba graczy jest nieparzysta (np. 3 lub 5), aplikacja przydziela wolne losy (BYE) w pierwszej rundzie.",
        host_step3_title: "ZWYCIĘZCA MECZU I WALKOWER",
        host_step3_desc: "Oznacz zwycięzcę, klikając jego nazwisko na drabince. Jeśli gracz odda mecz walkowerem, zaznacz rywala jako zwycięzcę.",
        host_step4_title: "DUŻE TURNIEJE",
        host_step4_desc: "Zorganizuj kilka osobnych grup eliminacyjnych (maks. 8 graczy w grupie). Wybierz 1–4 najlepszych graczy z każdej grupy i utwórz w aplikacji nowy \"turniej finałowy\", aby wyłonić mistrza."
    },
    zh: {
        rules_and_guide: "规则与指南",
        rules_official_rules: "官方规则",
        rules_host_tournament: "如何举办比赛",
        rules_btn_close: "关闭",
        rules_start_title: "开始",
        rules_start_desc: "石头剪刀布的赢家先发球。",
        rules_kickoff_title: "开球",
        rules_kickoff_desc: "必须在自己的球门区域内开球。",
        rules_position_title: "身体姿势",
        rules_position_desc: "双臀必须保持在长凳上。双手不得进入比赛区域，应放在桌面上或长凳两侧。",
        rules_ballout_title: "出界球",
        rules_ballout_desc: "如果球离开桌面，由球出界那一侧的球员开球重新开始比赛。",
        rules_winner_title: "获胜者",
        rules_winner_desc: "率先攻入3球的球员获胜。",
        host_step1_title: "选择 2-8 名球员",
        host_step1_desc: "输入球员姓名并开始比赛。",
        host_step2_title: "自动生成对阵图",
        host_step2_desc: "Subsoccer GO 会自动打乱比赛顺序并生成比赛对阵图。如果球员人数为奇数（例如 3 或 5 人），系统将在首轮分配轮空（BYE）。",
        host_step3_title: "胜负记录与弃权",
        host_step3_desc: "在对阵图中点击球员姓名来记录获胜者。若有球员弃权，则直接将对手标记为获胜者。",
        host_step4_title: "大型赛事",
        host_step4_desc: "可以分设多个独立的预选赛小组（每组最多 8 人）。选择各小组的前 1-4 名，在应用内创建一个新的“决赛”以角逐总冠军。"
    },
    ko: {
        rules_and_guide: "규칙 & 가이드",
        rules_official_rules: "공식 규칙",
        rules_host_tournament: "대회 개최 방법",
        rules_btn_close: "닫기",
        rules_start_title: "시작",
        rules_start_desc: "가위바위보 승자가 먼저 시작합니다.",
        rules_kickoff_title: "킥오프",
        rules_kickoff_desc: "킥오프는 반드시 자신의 골대 안쪽 영역에서 해야 합니다.",
        rules_position_title: "자세 고정",
        rules_position_desc: "양쪽 엉덩이는 항상 벤치에 닿아 있어야 합니다. 손은 경기 영역 안으로 들어가면 안 되며, 테이블 위나 벤치 옆에 두어야 합니다.",
        rules_ballout_title: "아웃 오브 플레이",
        rules_ballout_desc: "공이 테이블 밖으로 나가면, 공이 나간 쪽의 플레이어가 킥오프를 하여 경기를 재개합니다.",
        rules_winner_title: "우승자",
        rules_winner_desc: "먼저 3골을 넣는 플레이어가 승리합니다.",
        host_step1_title: "2-8명 플레이어 선택",
        host_step1_desc: "플레이어 이름을 입력하고 대회를 시작합니다.",
        host_step2_title: "토너먼트 대진표 자동 생성",
        host_step2_desc: "Subsoccer GO가 매치를 무작위로 섞어 토너먼트 대진표를 자동으로 생성합니다. 플레이어 수가 홀수(예: 3명 또는 5명)인 경우, 앱이 1회전 부전승(BYE)을 자동으로 배정합니다.",
        host_step3_title: "경기 승자 및 기권 기록",
        host_step3_desc: "대진표에서 플레이어 이름을 클릭하여 승자를 기록합니다. 기권한 플레이어가 있는 경우 상대방을 승자로 지정하세요.",
        host_step4_title: "대규모 대회 운영",
        host_step4_desc: "여러 개의 별도 예선 그룹(그룹당 최대 8명)을 생성하여 운영합니다. 각 예선 그룹의 상위 1-4명을 선정한 후, 앱에서 새로운 '결승 토너먼트'를 만들어 종합 우승자를 결정합니다."
    },
    ar: {
        rules_and_guide: "القواعد والدليل",
        rules_official_rules: "القواعد الرسمية",
        rules_host_tournament: "كيفية تنظيم بطولة",
        rules_btn_close: "إغلاق",
        rules_start_title: "البدء",
        rules_start_desc: "الفائز في لعبة حجر-ورقة-مقص يبدأ اللعب.",
        rules_kickoff_title: "ركلة البداية",
        rules_kickoff_desc: "يجب لعب ركلة البداية من داخل منطقة المرمى الخاصة بك.",
        rules_position_title: "وضعية اللعب",
        rules_position_desc: "يجب أن تظل كلتا الأردااف ملامسة للمقعد. يُمنع دخول اليدين إلى منطقة اللعب ويجب إبقاؤهما على الطاولة أو على جانبي المقاعد.",
        rules_ballout_title: "الكرة خارج الملعب",
        rules_ballout_desc: "إذا خرجت الكرة من الطاولة، يستأنف اللعب بركلة بداية من اللاعب الذي خرجت الكرة من جهته.",
        rules_winner_title: "الفائز",
        rules_winner_desc: "يفوز اللاعب الأول الذي يسجل 3 أهداف.",
        host_step1_title: "اختر 2-8 لاعبين",
        host_step1_desc: "أدخل أسماء اللاعبين وابدأ البطولة.",
        host_step2_title: "جدول مباريات تلقائي",
        host_step2_desc: "يقوم تطبيق Subsoccer GO بخلط المباريات وتوليد جدول البطولة تلقائياً. إذا كان عدد اللاعبين فردياً (مثل 3 أو 5 لاعبين)، يقوم التطبيق بتعيين جولة إعفاء (BYE) للدور الأول.",
        host_step3_title: "الفائز بالمباراة والانسحاب",
        host_step3_desc: "حدد الفائز عن طريق النقر على اسم اللاعب في جدول المباريات. إذا انسحب لاعب، قم بتمييز الخصم كفائز.",
        host_step4_title: "البطولات الكبيرة",
        host_step4_desc: "نظم عدة مجموعات تصفيات منفصلة (بحد أقصى 8 لاعبين لكل مجموعة). اختر أفضل 1-4 لاعبين من كل مجموعة وأنشئ \"بطولة نهائيات\" جديدة في التطبيق لتتويج البطل العام."
    },
    az: {
        rules_and_guide: "QAYDALAR & TƏLİMAT",
        rules_official_rules: "RƏSMİ QAYDALAR",
        rules_host_tournament: "TURNİRİN TƏŞKİLİ",
        rules_btn_close: "BAĞLA",
        rules_start_title: "BAŞLANĞIC",
        rules_start_desc: "Daş-Kağız-Qayçı oyununun qalibi oyuna başlayır.",
        rules_kickoff_title: "BAŞLANĞIC ZƏRBƏ",
        rules_kickoff_desc: "Başlanğıc zərbə öz qapı sahənizin daxilindən yerinə yetirilməlidir.",
        rules_position_title: "MÖVQEYİN SAXLANILMASI",
        rules_position_desc: "Hər iki omba oturacaqda qalmalıdır. Əllər oyun sahəsinə girməməli, masanın üzərində və ya oturacaqların yanlarında saxlanılmalıdır.",
        rules_ballout_title: "TOP OYUNDAN KƏNARDA",
        rules_ballout_desc: "Top masadan kənara çıxarsa oyun, topun çıxdığı tərəfdəki oyunçunun başlanğıc zərbəsi ilə yenidən başlayır.",
        rules_winner_title: "QALİB",
        rules_winner_desc: "3 qol vuran ilk oyunçu qalib gəlir.",
        host_step1_title: "2-8 OYUNÇU SEÇİN",
        host_step1_desc: "Oyunçu adlarını daxil edin və turniri başladın.",
        host_step2_title: "AVTOMATİK TURNİR CƏDVƏLİ",
        host_step2_desc: "Subsoccer GO oyunları qarışdırır və turnir cədvəlini avtomatik yaradır. Oyunçu sayı tək olarsa (məsələn, 3 və ya 5 oyunçu), proqram ilk mərhələ üçün azad oyun (BYE) təyin edir.",
        host_step3_title: "OYUNUN QALİBİ & TEXNİKİ MƏĞLUBİYYƏT",
        host_step3_desc: "Cədvəldə oyunçunun adına klikləyərək qalibi qeyd edin. Əgər oyunçu oyundan imtina edərsə, rəqibi qalib olaraq qeyd edin.",
        host_step4_title: "BÖYÜK TURNİRLƏR",
        host_step4_desc: "Bir neçə ayrıca seçmə qrupu təşkil edin (hər qrupda maksimum 8 oyunçu). Hər qrupdan ən yaxşı 1-4 oyunçunu seçin və final qalibini müəyyən etmək üçün proqramda yeni \"final turniri\" yaradın."
    }
};

const lines = content.split('\n');
let currentLang = '';
const processedLines = [];

for (let i = 0; i < lines.length; i++) {
    const line = lines[i];
    const langMatch = line.match(/^\s+([a-z]{2}):\s*\{/);
    if (langMatch) {
        currentLang = langMatch[1];
    }
    
    if (TRANSLATION_MAP[currentLang]) {
        let shouldSkip = false;
        for (const key of Object.keys(TRANSLATION_MAP[currentLang])) {
            if (line.trim().startsWith(`${key}:`)) {
                shouldSkip = true;
                break;
            }
        }
        
        if (shouldSkip) {
            continue;
        }
    }
    
    processedLines.push(line);
    
    if (line.includes('signup_back_login:') && TRANSLATION_MAP[currentLang]) {
        let updatedLine = processedLines.pop();
        if (!updatedLine.trim().endsWith(',')) {
            updatedLine += ',';
        }
        
        const map = TRANSLATION_MAP[currentLang];
        const keysText = Object.entries(map).map(([k, v]) => `        ${k}: ${JSON.stringify(v)}`).join(',\n');
        processedLines.push(updatedLine + '\n' + keysText);
    }
}

fs.writeFileSync(file, processedLines.join('\n'), 'utf8');
console.log('All 19 languages localized successfully!');
